### PR TITLE
Cesium

### PR DESCRIPTION
**Pull request by zoltantothcom**
[Cesium](https://cesiumjs.org/) - An open-source JavaScript library for world-class 3D globes and maps

### CODE REVIEW

**Comment by samiheikki** [comment]
Thanks @zoltantothcom. Will merge this and #182 after #181 is first merged. Just to make sure no additional rebase needed in that PR. Thanks for your patience!

**Comment by zoltantothcom** [comment]
I read through the comments for #181 after I submitted the PR-s, so was aware that they won't be merged right away - no worries :)

**Comment by ghost** [comment]
Hi @zoltantothcom

Please note that from now new logos should have an "url" property.

I think for Cesium its - https://cesiumjs.org/
and for React-Flight its - http://www.react-flight.io/

Thanks!

**Comment by zoltantothcom** [comment]
@maxvcode  Thanks! I'll update my PR-s when your changes get merged.

**Comment by samiheikki** [comment]
Hi @zoltantothcom Can you rebase this PR to master?

**Comment by zoltantothcom** [comment]
Hi Sami, I've updated the PR-s. Thanks!

**Pull request merged**
