### PR TITLE
Improve Result Page & More Meta Fields

### LINKED ISSUE #98: Allow Adding more meta to logos.json
Hi :) Thanks for this nice game.I'm going to add a couple of logos now, but when i was playing game, i expected to get a link to that library i don't know, possibly with adding a simple "url" field to logos.json. If you are ok with this i can open a PR for adding this link to UI too :)

### PR DESCRIPTION
**Pull request by pi0**
Hey. This PR adds supporting more JSON meta fields including: 
- Description of project
- GithubRepo in form of `owner/repo` (This helps us retrieving more information from Github API in feature)
- URL

Also, I've made some improvements to Result page including twitter share with a message :) 

image

Fixes #98

### CODE REVIEW

**Comment by samiheikki** [comment]
Thank you, looking good already. I'll test it better later today. For further improvements, would you like to continue or me to continue working with this PR?

**Comment by pi0** [comment]
@samiheikki Thanks :) Please let me informed about your tests and further improvements.

**Comment by samiheikki** [comment]
Sorry it will take me a few days to get back on this. I'm implementing the ranking system which will also change the result page a bit, so I'll get back in a few days for feedback.

**Comment by samiheikki** [comment]
I've now implemented the ranking and the result page changed a bit. I'm still looking forward for having this feature in the game. But I think it would be great that at the bottom there would be a text like "See the correct result" and after clicking it would show the logo and the text for it etc. Is that something you want to implement? Also rebase needed :)

**Comment by samiheikki** [comment]
Ping @pi0

**Comment by samiheikki** [comment]
Closing PR for long inactivity.

**Pull request closed without merging**
