### PR TITLE
Polished

### PR DESCRIPTION
**Pull request by zoltantothcom**
[Polished](https://polished.js.org/) - A lightweight toolset for writing styles in JavaScript

### CODE REVIEW

**Comment by tunnckoCore** [comment]
maybe cut the name?

**Comment by zoltantothcom** [comment]
@tunnckoCore not sure how can be "polished" cut?

**Comment by tunnckoCore** [comment]
most simply with paint if you win user, but there are online tools too

**Comment by zoltantothcom** [comment]
@tunnckoCore ooooh :) you mean cut the name off the image :) I was thinking about just the name "_Polished_" ))) and was like - hmm.. how can I cut the official name of the lib to make it shorter?..

**Comment by tunnckoCore** [comment]
Now looks a lot better to me :)

>  and was like - hmm.. 

Haha, yea :D

**Comment by samiheikki** [comment]
OMG! Over 200 logos!!!!

**Pull request merged**
