### PR TITLE
Generate added

### PR DESCRIPTION
**Pull request by zoltantothcom**
[Generate](https://github.com/generate) - A new command line tool and developer framework for scaffolding out GitHub projects. A more powerful, composable, functional alternative to Yeoman.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
@jonschlinkert congrats! say thank you for The Toolkit promoter - Charlike, haha :d

**Comment by tunnckoCore** [comment]
zoltan, and any other next adding from #40 ref in pr comments

**Comment by zoltantothcom** [comment]
@tunnckoCore yeah, I'm slowly going through your list #40 when work allows :)

**Comment by jonschlinkert** [comment]
indeed, thank you!

**Pull request merged**
