### PR TITLE
Add NativeScript-Angular

### PR DESCRIPTION
**Pull request by sis0k0**

### CODE REVIEW

**Comment by samiheikki** [comment]
Hi @sis0k0 awesome PR! Can you change the image's file name to match the framework's name. Meaning change underscore to a hyphen `nativescript-angular.png`

**Comment by sis0k0** [comment]
Fixed :)

**Comment by samiheikki** [comment]
Argh one more thing. Image seems to be 91x100 pixels. Can you increase the image's width to be 100x100 px. Thanks :)

**Comment by samiheikki** [comment]
Thanks @sis0k0! Merged

**Pull request merged**
