### PR TITLE
Added 32 new logos

### PR DESCRIPTION
**Pull request by TheFrankemon**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Cooooool :dagger: :dancer: :laughing:

**Comment by samiheikki** [comment]
OH MY! That is awesome! I'll take a look tonight/tomorrow. Thanks @francomontiel

**Comment by tunnckoCore** [comment]
yea i cloned the pr and tried it ;d finished in two tries hahaha.

**Comment by tunnckoCore** [comment]
franc, if u are interested and have time, look at my issue and pr them too :))

**Comment by samiheikki** [comment]
Works perfectly. Big thanks to you @francomontiel 🎉 🎉 🎉 🎉 🎉

**Comment by samiheikki** [comment]
https://javascript-game.firebaseapp.com/ has now 145 logos :)

**Pull request merged**
